name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.MY_ACTION_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  assign_one_project:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: AssignToProject
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_ACTION_TOKEN }}

    - name: Assign 'FEATURE REQUEST' to 'TRIAGE - FEATURE REQUEST'
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: contains(github.event.issue.labels.*.name, 'Feature Request')
      with:
          project: 'https://github.com/ecureuill/SELIProject/projects/3'
          column_name: 'NEEDS TRIAGE'
    - name: Assign 'BUG', 'ISSUE',' BUG ON NEXT RELEASE' label to 'TRIAGE - Bugs'
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        contains(github.event.issue.labels.*.name, 'bug') ||
        contains(github.event.issue.labels.*.name, 'bug on next release') ||
        contains(github.event.issue.labels.*.name, 'issues')
      with:
        project: 'https://github.com/ecureuill/SELIProject/projects/1'
        column_name: 'NEEDS TRIAGE'

    - name: Assign '1 - PLANNING' label to 'FEATURE SPECIFICATION'
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: contains(github.event.issue.labels.*.name, '1 - Planning')
      with:
        project: 'https://github.com/ecureuill/SELIProject/projects/4'
        column_name: 'PENDING FEATURE REQUEST'

    - name: Assign '2 - READY' label to 'DEVELOPMENT CYCLE'
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: contains(github.event.issue.labels.*.name, '2 - Ready')
      with:
        project: 'https://github.com/ecureuill/SELIProject/projects/2'
        column_name: 'TO-DO'

    - name: Assign 'need tester' label to 'FUNCTIONALITY TEST CYCLE'
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: contains(github.event.issue.labels.*.name, 'need tester')
      with:
        project: 'https://github.com/ecureuill/SELIProject/projects/6'
        column_name: 'TO-DO'

    - name: Assign 'Pull Request' to 'PULL REQUEST CYCLE'
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        github.event_name == 'pull_request' &&
        github.event.action == 'opened'
      with:
        project: 'https://github.com/ecureuill/SELIProject/projects/7'
        column_name: 'In progress'
