on:
  issues:
    types: [opened, labeled]
#   pull_request:
#     types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.MY_ACTION_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign issues 'feature request' label to project 3
      uses: ecureuill/SELIProject
      if: |
        contains(github.event.issue.labels.*.name, 'Feature Request')
      with:
        project: 'https://github.com/ecureuill/SELIProject/projects/3'
        column_name: 'NEEDS TRIAGE'
    - name: Assign issues 'bugs` label to project 1
      uses: ecureuill/SELIProject
      if: |
        contains(github.event.issue.labels.*.name, 'bug') ||
        contains(github.event.issue.labels.*.name, 'bug on next release') ||
        contains(github.event.issue.labels.*.name, 'issue')
      with:
        project: 'https://github.com/ecureuill/SELIProject/projects/1'
        column_name: 'Needs triage'
