name: main

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  project_card:
    types: [moved]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  triage:
    name: LabelWhenMoved
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/auto-card-labeler@v1   
  comment:
    needs: triage
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  assign_one_project:
    needs: triage
    runs-on: ubuntu-latest
    name: AssignToProject
    steps:
     - name: Assign 'FEATURE REQUEST' to 'TRIAGE - FEATURE REQUEST'
       uses: srggrs/assign-one-project-github-action@1.2.0
       if:  contains(github.event.issue.labels.*.name, 'feature request')
       with:
        project: 'https://github.com/ecureuill/SELIProject/projects/1'
        column_name: 'NEEDS TRIAGE'

     - name: Assign 'BUG', 'ISSUE',' BUG ON NEXT RELEASE' label to 'TRIAGE - Bugs'
       uses: srggrs/assign-one-project-github-action@1.2.0
       if: |
            contains(github.event.issue.labels.*.name, 'bug') ||
            contains(github.event.issue.labels.*.name, 'bug on next release') ||
            contains(github.event.issue.labels.*.name, 'issues')
       with:
        project: 'https://github.com/ecureuill/SELIProject/projects/1'
        column_name: 'NEEDS TRIAGE'
        
     - name: Assign '1 - PLANNING' label to 'FEATURE SPECIFICATION'
       uses: srggrs/assign-one-project-github-action@1.2.0
       if: contains(github.event.issue.labels.*.name, '1 - Planning')
       with:
        project: 'https://github.com/ecureuill/SELIProject/projects/4'
        column_name: 'PENDING FEATURE REQUEST'

     - name: Assign '2 - READY' label to 'DEVELOPMENT CYCLE'
       uses: srggrs/assign-one-project-github-action@1.2.0
       if: contains(github.event.issue.labels.*.name, '2 - Ready')
       with:
        project: 'https://github.com/ecureuill/SELIProject/projects/2'
        column_name: 'TO-DO'

     - name: Assign 'need tester' label to 'FUNCTIONALITY TEST CYCLE'
       uses: srggrs/assign-one-project-github-action@1.2.0
       if: contains(github.event.issue.labels.*.name, 'need tester')
       with:
        project: 'https://github.com/ecureuill/SELIProject/projects/6'
        column_name: 'TO-DO'

     - name: Assign 'Pull Request' to 'PULL REQUEST CYCLE'
       uses: srggrs/assign-one-project-github-action@1.2.0
       if: |
          github.event == 'pull_request' &&
          github.event.action == 'opened'
       with:
        project: 'https://github.com/ecureuill/SELIProject/projects/7'
        column_name: 'In progress'
