name: (s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
     - name: Assign FEATURE REQUEST and to project 3
       uses: srggrs/assign-one-project-github-action@1.2.0
       if:  contains(github.event.issue.labels.*.name, 'feature request')
       with:
        project: 'https://github.com/ecureuill/SELIProject/projects/1'
        column_name: 'NEEDS TRIAGE'

     - name: Assign BUG, ISSUE, BUG ON NEXT RELEASE label to project 1
       uses: srggrs/assign-one-project-github-action@1.2.0
       if: |
            contains(github.event.issue.labels.*.name, 'bug') ||
            contains(github.event.issue.labels.*.name, 'bug on next release') ||
            contains(github.event.issue.labels.*.name, 'issues')
       with:
        project: 'https://github.com/ecureuill/SELIProject/projects/1'
        column_name: 'NEEDS TRIAGE'
